### ISSUE TITLE
Add default constraint label

### ISSUE THREAD

**Issue by roper79** [OpenPonk/borm-editor#11]
It is possible to add a constraint to a transition, but the label is not displayed.

**Comment by roper79** [comment]
If no label is provided during adding of the contraint, it is very hard/impossible then to click on it and add it later.

An easy solution may be to provide a default label (such as "constraint") any time the label gets empty -- this covers the situation after adding the contraints and not setting its label, as well as deleting the label text afterwards.

**Comment by JanBliznicenko** [comment]
Fixed by using the default text
